name: Tests
on: [push]

jobs:
  test:
    strategy:
      matrix:
        java-version: ["8", "11", "17"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare java
        uses: actions/setup-java@v3.13
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java-version }}

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: 1.11.1.1413

      - name: Checkout
        uses: actions/checkout@v4.1

      - name: Run tests not Windows
        if: ${{ matrix.os != 'windows-latest' }}
        run: clojure -X:test
        shell: bash

      - name: Run tests on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: clojure -X:test
        shell: powershell
